name: Tests

on: push

jobs:
  build:
    name: CI Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          composer --version
          composer install --no-interaction
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Unit tests
        run: |
          php vendor/bin/phpunit